env:
  WINIT_X11_SCALE_FACTOR: "1.0"

window:
  decorations: full
  opacity: 0.2

colors:
  # Default colors
  primary:
    background: '0x2e2c28'
    foreground: '0xB3B1AD'

  # Normal colors
  normal:
    black: '0x01060E'
    red: '0xEA6C73'
    green: '0x91B362'
    yellow: '0xF9AF4F'
    blue: '0x53BDFA'
    magenta: '0xFAE994'
    cyan: '0x90E1C6'
    white: '0xC7C7C7'

  # Bright colors
  bright:
    black: '0x686868'
    red: '0xF07178'
    green: '0xC2D94C'
    yellow: '0xFFB454'
    blue: '0x59C2FF'
    magenta: '0xFFEE99'
    cyan: '0x95E6CB'
    white: '0xFFFFFF'

# window:
#   decorations: full
#   opacity: 1.0

# colors:
#   primary:
#     background: '0xf8f8f8'
#     foreground: '0x2a2b33'

#   normal:
#     black: '0x000000'
#     red: '0xde3d35'
#     green: '0x3e953a'
#     yellow: '0xd2b67b'
#     blue: '0x2f5af3'
#     magenta: '0xa00095'
#     cyan: '0x3e953a'
#     white: '0xbbbbbb'

#   bright:
#     black: '0x000000'
#     red: '0xde3d35'
#     green: '0x3e953a'
#     yellow: '0xd2b67b'
#     blue: '0x2f5af3'
#     magenta: '0xa00095'
#     cyan: '0x3e953a'
#     white: '0xffffff'

font:
  # Normal (roman) font face
  normal:
    # family: "monospace"
    # family: "NotoSansMono Nerd Font"
    family: "Source Code Variable"
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    # family: 'SF Mono'

    # The `style` can be specified to pick a specific face.
    style: Regular

    size: 11.0


