# env:
#   # WINIT_X11_SCALE_FACTOR: "1.0"
  # TERM: alacritty

window:
  decorations: full
  opacity: 1.0

colors:
  # Default colors
  primary:
    background: '0x2e2c28'
    foreground: '0xB3B1AD'

  # Normal colors
  normal:
    black: '0x01060E'
    red: '0xEA6C73'
    green: '0x91B362'
    yellow: '0xF9AF4F'
    blue: '0x53BDFA'
    magenta: '0xFAE994'
    cyan: '0x90E1C6'
    white: '0xC7C7C7'

  # Bright colors
  bright:
    black: '0x686868'
    red: '0xF07178'
    green: '0xC2D94C'
    yellow: '0xFFB454'
    blue: '0x59C2FF'
    magenta: '0xFFEE99'
    cyan: '0x95E6CB'
    white: '0xFFFFFF'

# window:
#   decorations: full
#   opacity: 1.0

# colors:
#   primary:
#     background: '0xf8f8f8'
#     foreground: '0x2a2b33'

#   normal:
#     black: '0x000000'
#     red: '0xde3d35'
#     green: '0x3e953a'
#     yellow: '0xd2b67b'
#     blue: '0x2f5af3'
#     magenta: '0xa00095'
#     cyan: '0x3e953a'
#     white: '0xbbbbbb'

#   bright:
#     black: '0x000000'
#     red: '0xde3d35'
#     green: '0x3e953a'
#     yellow: '0xd2b67b'
#     blue: '0x2f5af3'
#     magenta: '0xa00095'
#     cyan: '0x3e953a'
#     white: '0xffffff'

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xe1e2e7'
    foreground: '0x3760bf'

  # Normal colors
  normal:
    black:   '0xe9e9ed'
    red:     '0xf52a65'
    green:   '0x587539'
    yellow:  '0x8c6c3e'
    blue:    '0x2e7de9'
    magenta: '0x9854f1'
    cyan:    '0x007197'
    white:   '0x6172b0'

  # Bright colors
  bright:
    black:   '0xa1a6c5'
    red:     '0xf52a65'
    green:   '0x587539'
    yellow:  '0x8c6c3e'
    blue:    '0x2e7de9'
    magenta: '0x9854f1'
    cyan:    '0x007197'
    white:   '0x3760bf'

  indexed_colors:
    - { index: 16, color: '0xb15c00' }
    - { index: 17, color: '0xc64343' }
    
font:
  # Normal (roman) font face
  normal:
    # family: "monospace"
    # family: "NotoSansMono Nerd Font"
    # family: "Source Code Pro"
    # family: "Hack Nerd Font"
    family: "Hasklug Nerd Font"
    # family: "SauceCodePro Nerd Font"
    # family: "Iosevka Nerd font"
    # family: "Source Code Pro"
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    # family: 'SF Mono'

    # The `style` can be specified to pick a specific face.
    style: Regular

    size: 14.0
